# Generated by Django 4.2.11 on 2024-04-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitwiz_app', '0002_outfitwizcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitwizcustomer',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
