# Generated by Django 4.2.11 on 2024-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitwiz_app', '0003_alter_outfitwizcustomer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitwizcustomer',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='outfitwizcustomer',
            name='svn',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
